### ISSUE TITLE
1.0.1 Server - Not Complete

### ISSUE THREAD

**Issue by Marcellas** [TPPIC/Test-Pack-Please-Ignore-2C#2] opened 2016-11-04 02:44 UTC
Either: The server batch is missing a lot of files, or something is going hey wire when trying to just overwrite current server files with what is downloaded via the launcher. Either way, it quits and wont even run a GUI.
I've tried placing a "Pause" in the bat file, and have tried running the changes through java. No Error file is produced.

**Comment by m4sterP** [comment] 2016-11-04 03:47
Could not reproduce this with a fresh 1614 forge server.

**Comment by Marcellas** [comment] 2016-11-04 11:36
Did you just download the forge server from minecraft forge or did you receive it via curse or FTB. All that is in the server pack right now is the mods, config folder and a few text files for mod permissions and what not.

**Comment by m4sterP** [comment] 2016-11-04 16:14
I forgot to add the forge server files to the zip, I ask for absolution. It will be fixed soon.

**Comment by m4sterP** [comment] 2016-11-05 23:05
Update is out.

**Closed as completed by m4sterP** 2016-11-05 23:05 UTC
